### ISSUE TITLE
After updating the empire resources credits are null

### ISSUE THREAD

**Issue by JohannesHartUniKassel** [sekassel/stp-24-server-issues#25] opened 2024-07-17 14:37 UTC
**Describe the bug**
A clear and concise description of what the problem is.
After updating resources with events (option free in patch request enabled) the server returns null for credits.

**To Reproduce**
1. Create a game and empire
2. Change resources with the free option enabled
3. Do the get request
4. See error no credits

**Expected behavior**
There should be credits

**Additional context**
![grafik](https://github.com/user-attachments/assets/56a04ec3-f741-48cc-9e95-c9314cb593e8)

**Comment by Clashsoft** [comment] 2024-07-17 17:13
Please format your issue correctly and remove placeholder text.

Are you sending the request body like this:
```json
{
  "resources": {
    "energy": 10,
    "minerals": 20
  }
}
```
Or are you sending a map with all resources?
Perhaps you have an entry where the value is `null`.
Otherwise I can't reproduce/explain this.

**Comment by JohannesHartUniKassel** [comment] 2024-07-22 06:13
We send a request body like the above, but we didn't encounter this issue now so maybe there were a bug on our side

**Comment by Clashsoft** [comment] 2024-07-22 08:33
Ok then I will close this for now. Please re-open if you encounter this again.

**Closed as not planned by Clashsoft** 2024-07-22 08:33 UTC
Labels: bug, invalid
